name: Performance Profiling

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * 0"

jobs:
  profile:
    runs-on: [self-hosted, baseline]

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages

    steps:
      - name: Reset repository
        run: |
          git clean -ffdx -- report
          git reset --hard HEAD
          rm -rf work/llvm-build work/perf-llvm-build work/opt-out work/opt-out-baseline work/opt-out-current work/artifacts

      - uses: actions/checkout@v6
        with:
          submodules: false
          ref: main
          clean: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up python env
        run: uv sync

      - name: Install inferno
        run: cargo install inferno

      - name: Run perf profiling
        run: uv run scripts/perf.py
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN_READONLY }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: work/perf-report

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
