name: Pre-commit test

on:
  issue_comment:
    types: created

jobs:
  build:
    if: github.event.issue.number == 2 && github.event.sender.type == 'User' && !startsWith(github.event.comment.body, '>')
    runs-on: [self-hosted, pre_commit]

    permissions:
      issues: write
      contents: write

    timeout-minutes: 120

    steps:
      - name: Reset repository
        run: git clean -ffdx -- report && git reset --hard HEAD

      - uses: actions/checkout@v4
        with:
          submodules: false
          ref: main
          clean: false

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Set up python env
        run: uv sync

      - name: Run test
        id: test
        run: uv run scripts/ci.py test
        env:
          GITHUB_RUN_ID: ${{ github.run_id }}
          HF_TOKEN: ${{ secrets.HF_TOKEN_READONLY }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          GITHUB_TOKEN_LLVM: ${{ secrets.PAT_MEMBERSHIP }}
          OPENAI_API_URL: ${{ secrets.OPENAI_API_URL }}
          OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
          OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}
          USER: ${{ github.event.sender.login }}
          COMMENT_BODY: ${{ github.event.comment.body }}
          ISSUE_URL: ${{ github.event.issue.number }}

      - name: Upload IR diff artifacts
        if: steps.test.outputs.SHOULD_UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: pre-commit-ir-diffs-${{ github.run_id }}
          path: ${{ steps.test.outputs.ARTIFACT_DIR }}
